// Code generated by github.com/itzngga/goRoxy DO NOT EDIT.
package command

import (
	"github.com/itzngga/goRoxy/internal/handler"
	"github.com/zhangyunhao116/skipmap"
)

var Commands []*handler.Command
var StateMap *skipmap.StringMap[int]

func GetState(number string, types string) (int, bool) {
	return StateMap.Load(number + "-" + types)
}
func SetState(number string, types string, value int) {
	StateMap.Store(number+"-"+types, value)
}
func DelState(number string, types string) {
	StateMap.Delete(number + "-" + types)
}
func GenerateAllCommands() {
	StateMap = skipmap.NewString[int]()
	ButtonCommand()
	HiCommand()
	HydratedCommand()
	ImageButtonCommand()
	StickerCommand()
	UrlImageButtonCommand()
}

func AddCommand(command *handler.Command) {
	Commands = append(Commands, command)
}
